config/routes.rb
Rails.application.routes.draw do
  resources :line_orders
  resources :orders
  get 'pages/show'
  resources :line_items
  resources :carts
  resources :products
  devise_for :users
  get 'welcome/index'
  root 'products#index'



  resources :checkouts  

  scope '/checkout' do 
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :line_orders, dependent: :destroy

  # def total_price
  #   line_orders.to_a.sum {|item| item.total_price}
  # end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]

  # GET /orders or /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1 or /orders/1.json
  def show
    respond_to do |format|
      format.html { redirect_to root_path }
      format.js { }
    end
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.fetch(:order, {})
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/_show_order_details.html.erb
<div class="card p-5" id="email-chosen">
    <h5 class="card-title">date : <%= @order.created_at %></h5>
    <h6 class="card-title">by : <%= @order.user.username %> - <%= @order.user.email %></h6>
    <% @order_items = [] %>
    <% @order_items = @order.line_orders %>

    <p class="card-text">
      <ul>
        <p>items :</p>
        <% @order_items.each do |item| %>
          <li><%= item.product.title %> x <%= item.quantity %></li>
        <% end %>
      </ul>
    </p> 

    
  </div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders Recap</h1>

<hr>

<div class="container">
      <div class="row">

        <div class="col-md-5">

          <ul id="my-order">
          <h5>Date - Username</h5>
            <% @orders.each do |order| %>
              <li id="order<%= order.id %>">
                <%= link_to order.created_at, order_path(order), remote: true %> - by <%= order.user.username %>
              </li>
            <% end %>
          </ul>    
        </div>

        <div class="col-md-7">

          <h5>info</h5>
          <div id="order-show">

          </div>
          
        </div>
        
      </div>
    </div>

<hr>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/orders/show.js.erb
listOrder  = document.querySelectorAll('#my-order > *');
thisOrder = document.querySelector("#order" + <%= @order.id %>);

listOrder.forEach(n => n.classList.remove("btn-danger"));

orderContent = document.getElementById("order-show");

if (orderContent.childElementCount == 0){
  orderContent.insertAdjacentHTML("beforeend", "<%= j render 'show_order_details', order: @order %>");
  thisOrder.classList.add("btn-danger");
} else {
  orderContent.removeChild(orderContent.childNodes[1]); 
  orderContent.insertAdjacentHTML("beforeend", "<%= j render 'show_order_details', order: @order %>");
  thisOrder.classList.add("btn-danger");
};