config/routes.rb
Rails.application.routes.draw do
  resources :line_orders
  resources :orders
  get 'pages/show'
  resources :line_items
  resources :carts
  resources :products
  devise_for :users
  get 'welcome/index'
  root 'products#index'



  resources :checkouts  

  scope '/checkout' do 
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :line_items
  has_many :line_orders
  has_one_attached :avatar
  
  validates :title, :description, :price, :format, presence: true
  validates :title, length: {maximum: 140}
  validates :description, length: {maximum: 1000}


  # after_create :test_email_jet


  # def test_email_jet
  #   UserMailer.mailjet_email(self).deliver_now
  # end



  #const pour :format des Product
  #FORMAT = %w{png gif jpg}


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :price, :format, :avatar)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :format %>
    <%= form.text_area :format %>
  </div>




  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<br>
<br>
<br>
<br>
<br>
<br>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">

  <div>
    <div><h1 class="my-4">Welcome to the Kittens Business</h1></div>
    <div>
      <% if user_signed_in? %>
        <% if current_user.admin == true %>
          <%= link_to 'Add A New Product', new_product_path, :class => "btn btn-outline-danger mb-4" %>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
          <img class="card-img-top" src="<%= product.image_url %>" alt="">
          <div class="card-body">
            <h4 class="card-title"><a> <%= link_to product.title, product %></a></h4>
            <p class="card-text"><strong>Description : </strong><%= product.description %></p>
            <p class="card-text"><strong>Format : </strong> <%= product.format %></p>
            <p class="card-text"><%= product.price %>€</p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  
</div>
  

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="row container">
  <div class="col-lg-6">
    <h2><%= @product.title %></h2>
    <p><%= @product.description %></p>
    <p><strong>Price : </strong><%= @product.price %>$</p>
    <p><strong>Format : </strong><%= @product.format %></p>
    <div class="row">
  <div class="mr-4"><%= link_to 'Back', root_path, :class => "btn btn-outline-info mb-4" %></div>

      <% if user_signed_in? %>
        <div><%= button_to 'Add to cart', line_items_path(product_id: @product), :class => "btn btn-outline-success mb-4" %></div>
      <% else %> 
        <p>Si vous souhaitez achetez cet article vous devez vous loger<br>
        c'est par <%= link_to 'Ici', new_user_session_path, :class => "btn btn-outline-info mb-4" %></p>
      <% end %> 
    </div>
    <div>
    <% if user_signed_in? %>
      <% if current_user.admin == true %>
        <%= link_to 'Edit', edit_product_path(@product), :class => "btn btn-outline-danger mr-4"  %>
      <% end %>
    <% end %>
    </div>

  </div>
  <div class="col-lg-6">
    <img class="card-img-top" src="<%= @product.image_url %>" alt="">
  </div>
</div>