config/routes.rb
Rails.application.routes.draw do
  resources :line_orders
  resources :orders
  get 'pages/show'
  resources :line_items
  resources :carts
  resources :products
  devise_for :users
  get 'welcome/index'
  root 'products#index'



  resources :checkouts  

  scope '/checkout' do 
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_products(prod)
    current_item = line_items.find_by(product_id: prod.id)
    
    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: prod.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum {|item| item.total_price}
  end


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price.to_f * quantity.to_f
  end

end

app/models/line_order.rb
class LineOrder < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :line_orders, dependent: :destroy

  # def total_price
  #   line_orders.to_a.sum {|item| item.total_price}
  # end

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :line_items
  has_many :line_orders
  has_one_attached :avatar
  
  validates :title, :description, :price, :format, presence: true
  validates :title, length: {maximum: 140}
  validates :description, length: {maximum: 1000}


  # after_create :test_email_jet


  # def test_email_jet
  #   UserMailer.mailjet_email(self).deliver_now
  # end



  #const pour :format des Product
  #FORMAT = %w{png gif jpg}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  attr_accessor :login

  has_many :orders

  validates :username, presence: true, uniqueness: {case_sensitive: false}
  #format: {with: /\A[a-zA-Z0-9 _\.]*z/}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #after_create :welcome_send
  #after_create :welcome_send_v2

  
  # envoi un email post create user via lk'action mailer affichage local gem letter_opener
  # def welcome_send
  #   UserMailer.welcome_email(self).deliver_now
  # end

  # def welcome_send_v2
  #   Mailjet::Send.create(messages: [{
  #     'From'=> {
  #       'Email'=> 'giraud.nicolas@me.com',
  #       'Name'=> 'kitten team'
  #     },
  #     'To'=> [
  #       {
  #         'Email'=> 'giraud.nicolas@me.com',
  #         'Name'=> 'Nicolas'
  #       }
  #     ],
  #     'Subject'=> 'welcome',
  #     'TextPart'=> 'Mailjet email',
  #     'HTMLPart'=> '<h3>Dear passenger 1, welcome to <a href=\'https://www.mailjet.com/\'>Mailjet</a>!</h3><br />May the delivery force be with you!',
  #   }]
  #   )
  # end
  



  # permet d'ajouter username dans les conditions de log in
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup 
    if login = conditions.delete(:login)
      where(conditions.to_hash).where("lower(username) = :value OR lower(email) = :value", value: login.downcase).first
    else
      where(conditions.to_hash).first
    end
  end
  

end

app/controllers/avatar_controller.rb
class AvatarController < ApplicationController
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: %i[ show edit update destroy ]

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE
  def destroy
    
      # @cart_items = []
      # @cart_items = @cart.line_items
    
      # @new_order = Order.new(user_id: current_user.id)
      # @new_order.save

      # @cart_items.each do |item|
      #   @new_line_order = LineOrder.new(order_id: @new_order.id, product_id: item.product_id, quantity: item.quantity)
      #   @new_line_order.save
      # end


    @cart.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Cart was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "attempt to access invalid cart #{params[:id]}"
      redirect_to root_path, notice: "that cart doesn't exist"
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper




end

app/helpers/avatar_helper.rb
module AvatarHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/line_orders_helper.rb
module LineOrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<!--Notification venant de Devise, certainement a passer en partial-->

<div class="container">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
</div>

app/views/layouts/_footer.html.erb
<br>
<br>
<br>
<br>
<br>
<footer class="py-5 bg-dark fixed-bottom">
  <div class="container">

    <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="<%= products_path %>">Kittens</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link mr-3" <%= link_to "Mon Panier", {controller: "carts", action: "show", id: current_user.id} %></a>
            </li>
          <% end %>
          <div class="dropdown">
            <% if user_signed_in? %>
              <button class="btn btn-outline-danger dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                Get out
              </button>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
              <li class="dropdown-item"><%= current_user.email %></li>
              <li class="dropdown-item"><%= link_to "Editer Profil", edit_user_registration_path %></li>
              <li><hr class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
              <% if current_user.admin == true %>
                <li><hr class="dropdown-divider"></li>
                <li class="dropdown-item"><%= link_to "My admin page", orders_path %></li>
              <% end %>
              </ul>
            <% else %>
                <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                  Get in
                </button>
                <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                  <li class="dropdown-item"><%= link_to "Login", new_user_session_path %></li>
                  <li class="dropdown-item"><%= link_to "Sign up", new_user_registration_path %></li>
                </ul>
            <% end %>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KittenEshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>  
    <script src="https://js.stripe.com/v3/"></script>
    <body>
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash' %>
      <div class="container">
        <%= yield %>
      </div>
      <%= render 'layouts/footer' %>
      </body>
</html>

app/views/pages/show.html.erb
PAGE LOGIN 

<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>



PAGE SIGNIN 
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username, autofocus: true, autocomplete: "username" %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>
sign up